#! /usr/bin/env bash

# scraper entrypoint

# ideally invokes ruby scraper, jruby scraper, rubinius scraper, et. al.


# options
# - dryRun
# - overwrite
# - definitionPaths: (process.env.NODE_BUILD_DEFINITIONS || 'share/node-build').split(':')

# process.argv.forEach(function (arg) {
#   switch (arg) {
#     case '-f':
#     case '--force':
#       options.overwrite = true
#       break
#     case '-n':
#     case '--dry-run':
#       options.dryRun = true
#       break
#     case '--nodejs':
#       nodes.nodejs = nodejs
#       break
#     case '--iojs':
#       nodes.iojs = iojs
#       break
#   }
# })
#
# if (!Object.keys(nodes).length) {
#   nodes = { nodejs: nodejs, iojs: iojs }
# }
#
# for (var node in nodes) {
#   if (nodes.hasOwnProperty(node)) {
#     scrape(nodes[node], options)
#   }
# }
