#! /usr/bin/env bash

declare -a RUBIES

while [ $# -gt 0 ]; do
  case "$1" in
    -f | --force )
      OVERWRITE=true ;;
    -n | --dry-run )
      DRY_RUN=true ;;
    * )
      echo "invalid usage" >&2
      exit 1 ;;
  esac
  shift
done

IFS=: read -ra DEF_PATHS <<<"${RUBY_BUILD_DEFINITIONS:-share/ruby-build}"

file_exists() {
  local filename="$1"
  [ -n "$OVERWRITE" ] && return 1

  for p in "${DEF_PATHS[@]}"; do
    [ -f "$p/$filename" ] && return
  done
}

write_file() {
  local filename="${DEF_PATHS[0]}/$1"
  local definition="$2"

  if [ -n "$DRY_RUN" ]; then
    echo "Would write $filename"
    cat <<<"$definition"
  else
    cat > "$filename" <<<"$definition"
    echo "$filename written"
  fi
}

for ruby in "${RUBIES[@]}"; do
  . "lib/scrape_${ruby}.bash"

  scrape_"$ruby"
done
